name: Compile Project

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up make
      run: sudo apt-get install make

    - name: Compile with make
      run: make
